[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ldm"
version = "0.1"
description = "stable diffusion."
readme = "README.md"
dependencies = [
    "python",
    "pip",
    "cudatoolkit",
    "pytorch",
    "torchvision",
    "albumentations",
    "diffusers",
    "opencv-python",
    "pudb",
    "invisible-watermark",
    "imageio",
    "imageio-ffmpeg",
    "pytorch-lightning",
    "omegaconf",
    "test-tube",
    "streamlit",
    "einops",
    "torch-fidelity",
    "transformers",
    "torchmetrics",
    "kornia",    
    { git = "https://github.com/CompVis/taming-transformers.git", rev = "master" },
    { git = "https://github.com/openai/CLIP.git", rev = "main" },
    { path = "." }
]